export default {
    SET_SELECTED_USER: "SET_SELECTED_USER",
    CREATE_USER: "CREATE_USER",
    DELETE_USER: "DELETE_USER",
    UPDATE_USER: "UPDATE_USER",
    SET_AUTH_USER: "SET_AUTH_USER",
    POST_LOGIN_REQUEST: "POST_LOGIN_REQUEST",
    POST_LOGIN_FAIL: "POST_LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAIL: "FETCH_USERS_FAIL",
    FETCH_USER_DETAIL_SUCCESS: "FETCH_USER_DETAIL_SUCCESS",
    FETCH_USER_DETAIL_FAIL: "FETCH_USER_DETAIL_FAIL",
    FETCH_USER_DETAIL_REQUEST: "FETCH_USER_DETAIL_REQUEST"
}